language: ruby
rvm:
- 2.1.0
before_script:
- git clone --quiet --branch gh-pages https://github.com/blanketsheep/hachioji.git
  build/
- pushd build/
- git pull --quiet -u origin gh-pages
- git rm -rf ./*
- popd
- sudo apt-get update -qq
- sudo apt-get install -y libmagickcore-dev libxml2-dev libxslt1-dev
- npm install -g bower
- bower install
script:
- bundle exec middleman build --clean
after_success:
- openssl aes-256-cbc -k $DEPLOY_KEY_PASSPHRASE -in deploy_key.enc -d -a -out deploy_key
- chmod 600 deploy_key
- cp deploy_key ~/.ssh/github_hachioji_deploy_key
- echo -e "\nHost github.com" >> ~/.ssh/config
- echo -e "\tStrictHostKeyChecking no" >> ~/.ssh/config
- echo -e "\tIdentityFile ~/.ssh/github_hachioji_deploy_key" >> ~/.ssh/config
- pushd build/
- git add -A
- git commit -m Update
- git push --quiet git@github.com:blanketsheep/hachioji.git gh-pages
branches:
  only:
  - master
#  - develop
env:
  global:
  - secure: UGlbsiwsXArXwBgjrBNVBLV3du9rzfLlT1kinGHMIrJ80WjujEAU2qKNNYUC+GKzlle8fLoxl5ZQ0YegSCWBErVswNUUzf37Je9ijfUbuLgtkaMukFiMPgAnOO2tOA4byi0k9XosjZm3+YTUdVWpIKGZn3CZyJhvUo3BeHPvY6w=
  - GIT_COMMITTER_NAME="Travis CI (Shuma Yoshioka)"
  - GIT_AUTHOR_NAME="Travis CI (Shuma Yoshioka)"
  - GIT_COMMITTER_EMAIL="s64.stdio+travis@gmail.com"
  - GIT_AUTHOR_EMAIL="s64.stdio+travis@gmail.com"
  - JEKYLL_BUILD="gh-pages"
notifications:
  slack:
    secure: NgTjtYud+jTv3sAQY+atIsupAJMUVyNwu6I+hf1ezh2X3qsF0mW4g/3pAZzFpABk28UmC4FBLJ4yLfYee9qW5wMF1QIE7h8FmCSJsuMlh0oX8y3VYGT0tumZBZVlne8U7UU75oEnasa7KTWRYV5tORCVL4+InazNpxpKiyoWyZo=
