name: Your New Jekyll Site
exclude:
- README.md
- Gemfile
- Gemfile.lock
- deploy_key
- deploy_key.pub
- deploy_key.enc
pygments: true
timezone: Asia/Tokyo
markdown: kramdown
gems:
- jekyll-compass
- jekyll-coffeescript

