name: "八王子ウェブマガジン"
description: "This is subtitle."
exclude:
- README.md
- Gemfile
- Gemfile.lock
- deploy_key
- deploy_key.pub
- deploy_key.enc
pygments: true
timezone: Asia/Tokyo
markdown: kramdown
paginate: 5
gems:
- jekyll-compass
- jekyll-coffeescript

